server:
  servlet:
    context-path: /api
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: appuser
      password: appuser
      authentication-database: appdb
      database: appdb
